// <auto-generated />
using System;
using MMO_EF_Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMO_EF_Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240302022309_HelloMigration")]
    partial class HelloMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMO_EF_Core.Guild", b =>
                {
                    b.Property<int>("GuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GuildName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildID");

                    b.ToTable("Guild");
                });

            modelBuilder.Entity("MMO_EF_Core.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("OwnerID")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("MMO_EF_Core.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuildID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlayerID");

                    b.HasIndex("GuildID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("Index_Person_Name");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("MMO_EF_Core.Item", b =>
                {
                    b.HasOne("MMO_EF_Core.Player", "Owner")
                        .WithOne("OwnedItem")
                        .HasForeignKey("MMO_EF_Core.Item", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MMO_EF_Core.Player", b =>
                {
                    b.HasOne("MMO_EF_Core.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildID");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("MMO_EF_Core.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MMO_EF_Core.Player", b =>
                {
                    b.Navigation("OwnedItem");
                });
#pragma warning restore 612, 618
        }
    }
}
